[package]
name = "ganbare_backend"
version = "0.3.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[features]
specify_schema = []

[dependencies]
diesel = { version = "0.11", features = ["chrono", "large-tables"]}
diesel_codegen = {version = "0.11", default-features = false, features = ["postgres", "dotenv"] }
dotenv = "0.8"
rust-crypto = "0.2"
error-chain = { version = "0.10", default-features = false}
clap = "2.20"
chrono = { version = "0.3", features = ["serde"]}
rpassword = "0.3"
rand = "0.3"
rustc-serialize = "0.3"
binary_macros = "0.6"
env_logger = "0.4"
data-encoding = "1.1"
lazy_static = "0.2"
sharp_pencil = "0.4"
log = "0.3"
lettre = "0.6"
mime = "0.2"
tempdir = "0.3"
regex = "0.2"
unicode-normalization = "0.1"
try_map = "0.2"
handlebars = "0.25"
reqwest = "0.4"
r2d2 = "0.7"
r2d2-diesel = "0.11"
byteorder = "1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
magic = "0.12"
